version: '3'

networks:
  lan_network:
    driver: bridge

services:
  todoapplication:
      hostname: todo
      build: .
      ports:
        - 16000:5000
      links:
        - db:postgres
      depends_on:
        - db
      networks:
        -  lan_network

  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4
    links:
      - db:postgres
    depends_on:
      - db
    ports:
      - 20100:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ambient-it@gmail.com
      PGADMIN_DEFAULT_PASSWORD: p4ssw0rd
    # volumes:
    #  - /opt/pgadmin:/var/lib/pgadmin
    networks:
      - lan_network

  db:
    hostname: postgres
    image: systemdevformations/postgresql-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    ports:
      - 6432:5432
    networks:
      -  lan_network